language: scala
scala:
  - "2.11.6"
script:
  - sbt ++$TRAVIS_SCALA_VERSION test
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test
  - sbt ++$TRAVIS_SCALA_VERSION coverageAggregate
after_success:
  - bash <(curl -s https://codecov.io/bash)
