language: scala
scala:
  - "2.11.5"
before_script: cd core
script:
  - sbt ++$TRAVIS_SCALA_VERSION test
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test
after_success:
  - bash <(curl -s https://codecov.io/bash)
